<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '77a9df9aa1d5cf1b2bf324897cb236a3',
  'DATABASE_URL' => 'sqlite:///%kernel.project_dir%/var/data.db',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
