services:
  db:
    env_file: ".env.dev.local"
    image: mariadb:11.4.5
    restart: always
    command: --character-set-server=${MARIADB_CHARSET} --collation-server=${MARIADB_CHARSET_COLLATION} --bind-address=0.0.0.0
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  adminer:
    env_file: ".env.dev.local"
    image: adminer
    restart: always
    ports:
      - "10180:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db

volumes:
  database_data:
