<?php

namespace ContainerCSXCwRo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Npb1PqWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.npb1PqW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.npb1PqW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bancoHora' => ['privates', '.errored..service_locator.npb1PqW.App\\Entity\\BancoHoras', NULL, 'Cannot autowire service ".service_locator.npb1PqW": it needs an instance of "App\\Entity\\BancoHoras" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'bancoHora' => 'App\\Entity\\BancoHoras',
            'entityManager' => '?',
        ]);
    }
}
