<?php

namespace ContainerCSXCwRo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBancoHorasControlador2ControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.npb1PqW.App\Controller\BancoHorasControlador2Controller::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.npb1PqW'] ?? $container->load('get_ServiceLocator_Npb1PqWService'));

        if (isset($container->privates['.service_locator.npb1PqW.App\\Controller\\BancoHorasControlador2Controller::edit()'])) {
            return $container->privates['.service_locator.npb1PqW.App\\Controller\\BancoHorasControlador2Controller::edit()'];
        }

        return $container->privates['.service_locator.npb1PqW.App\\Controller\\BancoHorasControlador2Controller::edit()'] = $a->withContext('App\\Controller\\BancoHorasControlador2Controller::edit()', $container);
    }
}
