<?php

namespace ContainerNxNyRlM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBancoHorasControlador2ControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0HtkzgW.App\Controller\BancoHorasControlador2Controller::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0HtkzgW.App\\Controller\\BancoHorasControlador2Controller::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bancoHora' => ['privates', '.errored..service_locator.0HtkzgW.App\\Entity\\BancoHoras', NULL, 'Cannot autowire service ".service_locator.0HtkzgW": it needs an instance of "App\\Entity\\BancoHoras" but this type has been excluded in "config/services.yaml".'],
        ], [
            'bancoHora' => 'App\\Entity\\BancoHoras',
        ]))->withContext('App\\Controller\\BancoHorasControlador2Controller::show()', $container);
    }
}
