<?php

namespace ContainerNxNyRlM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBancoHorasControlador2ControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1G..Zgc.App\Controller\BancoHorasControlador2Controller::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1G..Zgc.App\\Controller\\BancoHorasControlador2Controller::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bancoHorasRepository' => ['privates', 'App\\Repository\\BancoHorasRepository', 'getBancoHorasRepositoryService', true],
        ], [
            'bancoHorasRepository' => 'App\\Repository\\BancoHorasRepository',
        ]))->withContext('App\\Controller\\BancoHorasControlador2Controller::index()', $container);
    }
}
