<?php

namespace ContainerDNSxKIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBancoHorasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0HtkzgW.App\Entity\BancoHoras' shared service.
     *
     * @return \App\Entity\BancoHoras
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0HtkzgW": it needs an instance of "App\\Entity\\BancoHoras" but this type has been excluded in "config/services.yaml".');
    }
}
