<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDNSxKIx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDNSxKIx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDNSxKIx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDNSxKIx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDNSxKIx\App_KernelDevDebugContainer([
    'container.build_hash' => 'DNSxKIx',
    'container.build_id' => '42e510c8',
    'container.build_time' => 1739379804,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDNSxKIx');
